---
apiVersion: v1
kind: Service
metadata:
  name: cerebro
  labels:
    app: cerebro
spec:
  ports:
  - name: web
    port: 9000
    protocol: TCP
    nodePort: 31900
  selector:
    app: cerebro
  type: NodePort