---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cerebro
spec:
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      containers:
      - name: cerebro
        image: yannart/cerebro:latest
        ports:
        - containerPort: 9000