---
apiVersion: v1
kind: Service
metadata:
  name: kafka-test-client
  labels:
    app: kafka-test-client
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: kafka-test-client
  type: NodePort