---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
spec:
  ports:
  - port: 9200
    name: elasticsearch9200
    protocol: TCP
  - port: 9300
    name: elasticsearch9300
    protocol: TCP
  selector:
    app: elastic-search
  type: NodePort