---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-ui
spec:
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: sheepkiller/kafka-manager:stable
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: "zoo1:2181"
        - name: APPLICATION_SECRET
          value: "letmein"