---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kibana
spec:
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.2.4
        ports:
        - containerPort: 5601
