---
apiVersion: v1
kind: Service
metadata:
  name: logstash-indexer
  labels:
    app: logstash-indexer
spec:
  ports:
  - name: logstash
    port: 5044
    protocol: TCP
  selector:
    app: logstash-indexer
  type: NodePort