---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper-ui
spec:
  template:
    metadata:
      labels:
        app: zookeeper-ui
    spec:
      containers:
      - name: zoo-ui
        image: tobilg/zookeeper-webui
        ports:
        - containerPort: 8080
        env:
        - name: ZK_DEFAULT_NODE
          value: "zoo1"