---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-ui
  labels:
    app: zookeeper-ui
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: zookeeper-ui
  type: NodePort