---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  ports:
  - port: 3000
    name: web
    protocol: TCP
    nodePort: 31997
  selector:
    app: grafana
  type: NodePort