---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: grafana
spec:
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
